### PR TITLE
Fixed event handling in RN >= 0.39

### LINKED ISSUE #108: [BUG] onChangeState  doesn't work on RN 0.40
onProgress doesn't work too

### LINKED ISSUE #110: Events not firing on RN 0.39
Hey,

I'm using react-native `0.39` and no events are firing on IOS (`onReady`, `onChangeState`,...)
I didn't see any issues on it, am I the only one?

I fixed it by using `sendAppEventWithName` instead of `sendInputEventWithName ` to dispatch events from React Native to JS. Btw it seems that `sendInputEventWithName` is deprecated.

It might be the same issue as #108?

If anyone is having the same issue, I will do a PR ;)

### PR DESCRIPTION
**Pull request by wcandillon**
fixes #110 
fixes #108

### CODE REVIEW

**Comment by iDams** [comment]
Awesome!
Is it working on Android already?
I only made changes on iOS because I can't test on Android for now.

File: YTPlayerView/YTPlayerView.m [hunk 1]
```diff
@@ -114,8 +114,8 @@ - (void)stopVideo {
 - (void)seekToSeconds:(float)seekToSeconds allowSeekAhead:(BOOL)allowSeekAhead {
   NSNumber *secondsValue = [NSNumber numberWithFloat:seekToSeconds];
   NSString *allowSeekAheadValue = [self stringForJSBoolean:allowSeekAhead];
-  NSString *command = [NSString stringWithFormat:@"player.seekTo(%@, %@);", secondsValue, allowSeekAheadValue];
-  [self stringFromEvaluatingJavaScript:command];
+  NSString *command = [NSString stringWithFormat:@"player.seekTo(%@, false);", secondsValue];
```
Comment (iDams) [inline YTPlayerView/YTPlayerView.m]: I've changed the `allowSeekAheadValue` to be always `false` because this is what I wanted in my case but it might be better if we use the parameter `allowSeekAheadValue` . 

I've noticed that this parameter is set to `true` in `RCTYouTubeManager.m`. it might be nice to let the user set it in `<YouTube />` component. 
So be able to do something like this: `this.refs.player.seekTo(20, false)` :)

Comment (wcandillon) [inline YTPlayerView/YTPlayerView.m]: 👍

**Comment by wcandillon** [comment]
@iDams I can't test android for now either, it will take me some time before I can get to it.
